@startuml
'https://plantuml.com/class-diagram

interface Function {
    + apply(): Double
    + toString(): String
    + listVariables(): List<String>
}

class Number implements Function {
    - value: Double
    + apply(): Double
    + toString(): String
    + listVariables(): List<String>
}

class Variable implements Function {
    - name: String
    + apply(): Double
    + toString(): String
    + listVariables(): List<String>
}

class Divide implements Function {
    - listVariables(x: List<String>, y: List<String>): List<String>
    + apply(): Double
    + toString(): String
    + listVariables(): List<String>
}

class Minus implements Function {
    - listVariables(x: List<String>, y: List<String>): List<String>
    + apply(): Double
    + toString(): String
    + listVariables(): List<String>
}

class Multiply implements Function {
    - listVariables(x: List<String>, y: List<String>): List<String>
    + apply(): Double
    + toString(): String
    + listVariables(): List<String>
}

class Sum implements Function {
    - listVariables(x: List<String>, y: List<String>): List<String>
    + apply(): Double
    + toString(): String
    + listVariables(): List<String>
}

class Power implements Function {
    - listVariables(x: List<String>, y: List<String>): List<String>
    + apply(): Double
    + toString(): String
    + listVariables(): List<String>
}

class Root implements Function {
    - listVariables(x: List<String>): List<String>
    + apply(): Double
    + toString(): String
    + listVariables(): List<String>
}

class Module implements Function {
    - listVariables(x: List<String>): List<String>
    + apply(): Double
    + toString(): String
    + listVariables(): List<String>
}

@enduml